baseURL = "https://neel04.github.io/my-website/"
languageCode = 'en-us'
title = 'Neel Gupta'
theme = 'typo'

googleAnalytics = "G-PKTR8X5Y1X"

[params]
# Meta description
description = "Neel Gupta's Homepage"

# Appearance settings
theme = 'light'
colorPalette = 'gruvebox'
hideHeader = true

# Intro on main page, content is markdown
homeIntroTitle = 'Hey! ðŸ‘‹'
homeIntroContent = """
I'm Neel, an undergrad currently studying Data Science & AI in Ireland.
I'm particularly interested in Deep Learning research, and often spend my time reading papers
and exploring new ideas.
"""

# Collection to display on home
# Comment this out to remove it from homepage
# homeCollectionTitle = 'projects'
# homeCollection = 'projects'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "github"
url = "https://github.com/neel04"

[[params.social]]
name = "twitter"
url = "https://x.com/awesome_ruler_"

[[params.social]]
name = "email"
url = "mailto:neelgupta04@outlook.com"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/neel-gupta-b6236a331"

# Main menu pages
[[params.menu]]
name = "home"
url = "/my-website/"

[[params.menu]]
name = "projects"
url = "/my-website/projects"

[[params.menu]]
name = "blog"
url = "/my-website/blog/"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'
noClasses = false
guessSyntax = true

[markup.goldmark.parser]
wrapStandAloneImageWithinParagraph = false

[markup.goldmark.parser.attribute]
block = true

[markup.goldmark.renderer]
unsafe = true

# Giscus comments
[params.giscus]
enable = false
repo = "neel04/my-website"
repoid = "R_kgDOMWylMg"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"
